### ISSUE TITLE
Default color for icon that specified in component styles has bigger priority than CSS class color

### ISSUE THREAD

**Issue by aodinok** [gorangajic/react-icon-base#10]
In our project we are using CssModules and react-icons. We specifying colors/size and other possible properties thru CSS styles by assigning styleName to icon, which is converted by CssModules to className. With last changes all icons in our project has one color that specified as default for BaseIcon component. The problem is that this default color has bigger priority than color that we specify by setting CSS class name for icon. Guys do you agree that color is better to hold in CSS styles than in React component  props?
![3b86c0ce-4437-11e6-840e-631f970d0932](https://cloud.githubusercontent.com/assets/11699084/16701828/0d324da8-456b-11e6-8e0d-bf7ed24f7607.png)

**Comment by bentatum** [comment]
this should be fixed as of v2.0.3
