### ISSUE TITLE
run build and push to npm

### ISSUE THREAD

**Issue by Prinzhorn** [gorangajic/react-icon-base#2]
main is set to `lib/index.js` which still has `fill: "#000",`. I assume you didn't run `npm build` before publishing 0.0.6

**Comment by gorangajic** [comment]
sorry, it's now

**Comment by Prinzhorn** [comment]
thanks! Make sure to also push react-icons as it references the exact version https://github.com/gorangajic/react-icons/blob/be86ab046d8aaf0c25b75fe597e30530b095d88f/package.json#L55

**Comment by gorangajic** [comment]
done that also, thanks
```npm install react-icons@0.2.1```
