### ISSUE TITLE
Default size

### ISSUE THREAD

**Issue by Prinzhorn** [gorangajic/react-icon-base#3]
I was wondering why the size defaults to 24? Is there any specific reason? If not, do you think its reasonable to default it to `1em`? I'm not sure if this would have side effects, but I assume having the icon the same size as the text is more reasonable default than 24 pixels.

**Comment by gorangajic** [comment]
sure open up pull request, anyway I always pass the size prop

**Comment by Prinzhorn** [comment]
I'm planning to migrate away from font icons to inline svg and this would make it even easier because the svg behaves like the font icon. Will PR
