### ISSUE TITLE
Warning: Unknown prop `fit` on <svg> tag (React 15.2.0)

### ISSUE THREAD

**Issue by elado** [gorangajic/react-icon-base#9]
```
Warning: Unknown prop `fit` on <svg> tag. Remove this prop from the element.
For details, see https://fb.me/react-unknown-prop
    in svg (created by IconBase)
    in IconBase (created by MdVolumeUp)
```

**Comment by AleksandrZhukov** [comment]
Seems that it can be removed ([list of svg attributes](https://developer.mozilla.org/ru/docs/Web/SVG/Attribute))

**Comment by gorangajic** [comment]
https://github.com/gorangajic/react-icon-base/commit/b0022b7232c611ad38a4d2877ca56f570227c052

**Comment by AleksandrZhukov** [comment]
Also need to update [here](https://github.com/gorangajic/react-icons/blob/master/package.json#L59)
